#!/bin/bash
set -e
set -x

if ! git diff-index --quiet HEAD --; then
    echo "there are uncommitted changes, please commit first."
    exit 2
fi

git checkout gh-pages

cp -r dist/* .

if ! git diff-index --quiet HEAD --; then
    git commit -am "synced gh-pages from latest build on master"
    echo "you may want to run git push --all now."
else
    echo "there are no changes, wasting my time useless idiot?"
fi

git checkout master
